name: "Release to RC"

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: "Deploy to Release Candidate"
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: "Deploy to Vercel"
        id: "vercel_deployment"
        run: |
          echo "URL=$(npx vercel --token ${VERCEL_TOKEN})" >> $GITHUB_OUTPUT

      - name: "Alias deployment URL"
        run: |
          npx vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_SCOPE }} set ${{ steps.vercel_deployment.outputs.URL }} frantisek-kasik-rc.vercel.app
