name: "Release to Production"

on:
  release:
    types: [published]

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy"
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: "Deploy to Vercel"
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
